# Configuration file for the ABM land use land cover change agent based model

# full path with file name and extension to the counties shapefile
f_counties_shp: '/Users/kek25/Desktop/Data/shp/counties_srb.shp'

# full path with file name and extension to the land class category key file
f_key_file: '/Users/kek25/Desktop/Data/CDL2GCAM_categories.csv'

# gcam raster
f_gcam_file: '/Users/kek25/Desktop/Data/gcam_2010_domain_3000.tiff'

# profits file
f_profits_file: '/Users/kek25/Desktop/Data/GenerateSyntheticPrices_test_output.csv'

# output directory
output_directory: '/Users/kek25/Desktop/Data/Results'

# number of time steps
nt: 20

# list of lists for switching averse, tolerant, and neutral parameters (alpha, beta)
switch_params: [[4.5, 1.0], [0.5, 3.0], [2.0, 2.0]]

# boolean of whether to base switching parameters on farmer attributes or not
attr: True

# proportion of each switching type, lower than p is averse, higher is tolerant
p: 0.5

# fraction of current profit at which the CDF is zero and one, and number of points to generate
fmin: 1.0
fmax: 1.5
n: 100

# TODO:  Set seed for test data
# Seed for random number generator
crop_seed_size: 5

# initialization year
initialization_yr: 2010

# scale of grid in meters
scale: 3000

# list of counties to evaluate
county_list: ['Ada', 'Canyon']

# Currently available agent attributes, tenure status and area operated
agent_variables: ["TENURE", "AREA OPERATED"]

# NASS years that are available are 2007, 2012
nass_year: 2007

# state where NASS data is pulled from, as capatalized acronym
state: 'ID'

# List of counties used to gather NASS data, must be capitalized
nass_county_list: ['ADA', 'CANYON']

# NASS API key
nass_api_key:  'B5240598-2A7D-38EE-BF8D-816A27BEF504'