
# Configuration file for Janus, an agent based model of land use and land cover change

# directory for all initialization files
f_input_dir: '<Full path to the directory where input files are>'

# raster of the initial land cover data
f_init_lc_file: '<Full path with file name and extension of the initial land cover tiff>'

#profit choice flag, gcam or generated
profits: 'gcam'

# TODO have these run from within this script, taking in nt and setting nc
# profits file
f_profits_file: '<Full path with file name and extension to the profits csv file>'
f_gcam_profits_file: '<Full path with file name and extension to the GCAM USA profits csv file>'

# full path with file name and extension to the land class category key file
f_key_file: '<Full path with file name and extension to the crop conversion csv file>'

# output directory
output_directory:'<Full path with file name and extension to the output directory>'

# number of time steps
nt: 30

# list of lists for switching averse, tolerant, and neutral parameters (alpha, beta)
switch_params: [[4.5, 0.5], [0.25, 4.0], [2.0, 2.0]]

# boolean of whether to base switching parameters on farmer attributes or not
attr: False

# proportion of each switching type (0.95 = switching tolerant)
p: 0.95

# fraction of current profit at which the CDF is zero and one, and number of points to generate
fmin: 1.0
fmax: 1.5
n: 100

# TODO:  Set seed for test data
# Seed for random number generator
crop_seed_size: 5

# initialization year
initialization_yr: 2010

# scale of grid in meters
scale: 3000

# Currently available agent attributes, tenure status and area operated
agent_variables: ["TENURE", "AREA OPERATED"]

# NASS years that are available are 2007, 2012
nass_year: 2007

# state where NASS data is pulled from, as capitalized acronym
state: 'ID'

#list of counties for spatial sub setting
county_list: ['Ada', 'Canyon']

# List of counties used to gather NASS data, must be capitalized
nass_county_list: ['ADA', 'CANYON']

# NASS API key
nass_api_key:  'B5240598-2A7D-38EE-BF8D-816A27BEF504'